### ISSUE TITLE
animation jitter with mana relays, mana splitters, glyph presses

### ISSUE THREAD

**Issue by boneskull** [baileyholl/Ars-Nouveau#163] opened 2021-01-30 20:57 UTC
This shows the jitter w/ a mana relay, but this also affects mana splitters and glyph presses.  I'm guessing it is an interaction between Ars and another mod in the pack ([Enigmatica 6](https://github.com/NillerMedDild/Enigmatica6/)).  

Will cross-reference this to Enigmatica's tracker.

https://user-images.githubusercontent.com/924465/106367863-9b31a480-62fa-11eb-8576-ec9f38a765f5.mp4

Maybe useful info:

- MC 1.16.4
- Forge 35.1.37
- Enigmatica 1.39
- No Optifine; all vanilla lighting/texture settings at max
- 3440 x 1440 resolution
- RTX 2070 super
- OpenJDK runtime bundled w/ GDLauncher; "8u242-b08"

**Comment by NillerMedDild** [comment] 2021-01-30 21:38
I cannot reproduce this in E6 v0.3.12 in-dev, which uses `ars_nouveau-1.16.4-1.11.3`
E6 v0.3.9 used `ars_nouveau-1.16.4-1.11.2`

**Comment by baileyholl** [comment] 2021-01-30 22:10
This is related to Geckolib, should be fixed on the latest version of geckolib.

**Closed by baileyholl** 2021-01-30 22:10 UTC

**Comment by boneskull** [comment] 2021-01-30 22:55
ty
