### ISSUE TITLE
[BUG] Duping with Sribe's Table and Tinker's Contstructs' Crafting Station

### ISSUE THREAD

**Issue by dumbdemon** [baileyholl/Ars-Nouveau#695] opened 2022-09-13 15:53 UTC
### Versions
Ars Nouveau - 2.7.8
Tinker's Construct - 3.5.1.31
Curios API (Forge) - 5.0.7.1
GeckoLib - 3.0.38
Mantle - 1.9.27
Patchouli - 71.1

### What happens:
There's a duplication glitch with the interaction between the crafting station and Ars Nouveau's Scribe's Table when placed next to each other in 1.18.2. It showed up in All the Mods 7 and I tried it again with only just the two mods and its dependencies. When placed next to each other the crafting station detects the scribe's table inventory. When you place a item with at least two ore more into that inventory and try to take it out with out shift-clicking it creates a new stack and lessens what's in the detected inventory by one.
Duplicate issue was created on [Tinkers Construct](https://github.com/SlimeKnights/TinkersConstruct) git: SlimeKnights/TinkersConstruct#4994

**Comment by KnightMiner** [comment] 2022-11-23 06:47
For the record, all we do s access the item handler capability and use the methods from `IItemHandlerModifiable`. If your item handler is not going to behave properly when used in a UI, there is no reason to implement `IItemHandlerModifiable`. We also have a tag to blacklist it.

This bug looks to be caused by this very suspect code here: https://github.com/baileyholl/Ars-Nouveau/blob/1.19.x/src/main/java/com/hollingsworth/arsnouveau/common/block/tile/ScribesTile.java#L341-L346. I see no way that making a copy of the stack and shrinking by one will not cause dupes. A copy with stack size 1 (e.g. a stack.split) would work fine.

**Comment by sprocketaudio** [comment] 2022-12-19 17:21
Has this been fixed for 1.18 or no?

**Comment by Alexthw46** [comment] 2022-12-24 11:50
no, fix only merged for 1.19

**Comment by baileyholl** [comment] 2022-12-28 21:13
Fixed in latest

**Closed by baileyholl** 2022-12-28 21:13 UTC

**Comment by AnAwesomGuy** [comment] 2024-10-10 02:55
this got unfixed: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5803

**Comment by KnightMiner** [comment] 2024-10-10 03:04
No, it did not get unfixed. It was clearly stated above this was only fixed in 1.19, not 1.18. For 1.18, just use the blacklist tag Tinkers' Construct provides and hope that nothing else triggers the dupe bug.

**Comment by UnRealDinnerbone** [comment] 2025-02-19 16:53
Unless I'm blind, what is the tag for blacklisting stuff. I can't seem to find it

**Comment by KnightMiner** [comment] 2025-02-20 00:08
If you are on 1.20.1, its a whitelist. Check the tags for a chest block to find it.

if you are on 1.19.2 or earlier, its a blacklist. Check the tags for a furnace to find it.
