### ISSUE TITLE
[Request] Change the Spellbook so you change spells by sneaking while scrolling, rather than having 2 dedicated keys

### ISSUE THREAD

**Issue by aaronhowser1** [baileyholl/Ars-Nouveau#243] opened 2021-05-25 16:31 UTC
There's only so many keys on a keyboard, and this doesn't have to use two of them

**Comment by baileyholl** [comment] 2021-06-25 02:22
Duplicate of https://github.com/baileyholl/Ars-Nouveau/issues/134

**Closed by baileyholl** 2021-06-25 02:22 UTC
