### ISSUE TITLE
Volcanic Accumulator lava creation mismatch between book and reality

### ISSUE THREAD

**Issue by PhillZitt** [baileyholl/Ars-Nouveau#83] opened 2020-12-01 04:41 UTC
The book indicates that the Volcanic Accumulator "will [...] convert [...] to lava in a 3x3 given that these blocks exist beneath it in its 3x3 area." ( i.e. a 3x3 area centered on itself, one block down), but it instead creates lava in a 5x5 area centered on itself, one block down. Is the book correct, or is the entity correct?

![2020-11-30_21 34 47](https://user-images.githubusercontent.com/1178792/100698003-a5fca700-3354-11eb-8e7a-8e59f253de71.png)

**Comment by baileyholl** [comment] 2020-12-02 00:48
3x3 was intended, fixed in next update. Thank you.

**Closed by baileyholl** 2020-12-02 00:48 UTC
