### ISSUE TITLE
Crash in Creative Menu

### ISSUE THREAD

**Issue by Gaxon1** [baileyholl/Ars-Nouveau#443] opened 2022-01-29 07:14 UTC
ars_nouveau-1.18.1-2.1.1.jar
Forge 39.0.59

Details:
	Item Type: creative_spell_book
	Registry Name: ars_nouveau:creative_spell_book
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174235_(ItemRenderer.java:299) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174277_(ItemRenderer.java:290) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115203_(ItemRenderer.java:270) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_98581_(CreativeModeInventoryScreen.java:806) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_7286_(CreativeModeInventoryScreen.java:691) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6305_(AbstractContainerScreen.java:93) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:flytre_lib.mixins.json:storage.upgrade.HandledScreenMixin,pl:mixin:APP:itemborders.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_6305_(EffectRenderingInventoryScreen.java:30) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rei.mixins.json:MixinEffectRenderingInventoryScreen,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_6305_(CreativeModeInventoryScreen.java:607) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:395) ~[forge-1.18.1-39.0.59-universal.jar%23298!/:?] {re:mixin,re:classloading,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:388) ~[forge-1.18.1-39.0.59-universal.jar%23298!/:?] {re:mixin,re:classloading,pl:mixin:A,pl:epic_rei_lmao:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:886) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:voidscape:camerahurt,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#createLevel,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:unionlib.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:epic_rei_lmao:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23294!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.59.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by Gaxon1** [comment] 2022-01-29 07:29
This ended up being an issue with geckolib-1.18-forge-3.0.10, I reverted to 3.0.9 and the crash stopped occurring.

**Comment by C0rn3j** [comment] 2022-01-29 15:41
Dupe of #440

**Comment by baileyholl** [comment] 2022-01-30 02:27
Fixed on the latest version.

**Closed by baileyholl** 2022-01-30 02:27 UTC
